"""
Prints what the indicator resolver actually scores, against the real embedding
model, for a set of known-answer questions.

Why this exists: two opposite failures showed up in the same live run, and
neither can be fixed by guessing at a number.

  "How fast are prices rising?"      -> not_found, but should reach Inflation
  "What % of energy is solar?"       -> resolved to "Share of Qatari Teachers"

MIN_CONFIDENCE (0.55) is therefore too high for one and too low for the other,
which means the threshold cannot be tuned from either example alone — you need
the score DISTRIBUTION over a set of questions whose right answers are known.
That requires the real bge-m3 model, so this must run on the VM. Simulated
embeddings tell you nothing about calibration.

Run:
    docker compose exec api python scripts/calibrate_resolver.py

Read the output like this:
  - a "should match" row whose top score is BELOW the threshold is a false
    negative (the Inflation case) -> the threshold is too high, or the phrase
    needs the query-side prefix bge-m3 expects
  - a "should NOT match" row whose top score is ABOVE it is a false positive
    (the solar/teachers case) -> the threshold is too low
  - the GAP column is the margin to the runner-up; a small gap on a correct
    answer means the ambiguity check is close to firing

Pick MIN_CONFIDENCE above the highest false positive and below the lowest true
positive. If no such value exists, the scoring itself needs work (weights, or a
query prefix), not the threshold.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.resolvers.indicator_resolver import (
    _fetch_catalog, _similarity, EMBED_WEIGHT, STRING_WEIGHT,
    MIN_CONFIDENCE, MIN_GAP_TO_RUNNER_UP, has_usable_definition,
)
from app.resolvers.embeddings import get_embedding, cosine_similarity, embed_catalog

# (question phrase, expected indicator name or None if it should NOT match)
# Drawn from the QC workbook and the live run. Add your own as you find them.
CASES = [
    ("inflation", "Inflation"),
    ("How fast are prices rising", "Inflation"),
    ("the inflation rate", "Inflation"),
    ("GDP", "Real GDP"),
    ("Real GDP", "Real GDP"),
    ("economic output adjusted for prices", "Real GDP"),
    ("tourists arrived", "Number of International Visitors"),
    ("How many tourists arrived into Qatar", "Number of International Visitors"),
    ("international visitors", "Number of International Visitors"),
    # Should find NOTHING — the data has no solar/energy indicator at all.
    # This is the case that produced "Share of Qatari Teachers".
    ("What percentage of Qatar's energy is generated by solar", None),
    ("solar energy share", None),
    ("number of penguins in Qatar", None),
]


def main():
    catalog = [r for r in _fetch_catalog() if (r.get("data_point_count") or 0) > 0]
    names = [r["name_en"] for r in catalog]
    print(f"catalog: {len(catalog)} entries with data")
    print(f"MIN_CONFIDENCE={MIN_CONFIDENCE}  MIN_GAP_TO_RUNNER_UP={MIN_GAP_TO_RUNNER_UP}")
    print(f"scoring: {EMBED_WEIGHT}*embedding + {STRING_WEIGHT}*string\n")

    print("embedding the catalog (first run is slow)...", flush=True)
    name_embeddings = embed_catalog(names)

    false_pos, true_pos = [], []
    print(f"\n{'VERDICT':9} {'TOP':6} {'GAP':6}  {'QUESTION':42}  MATCHED")
    print("-" * 110)

    for phrase, expected in CASES:
        pe = get_embedding(phrase)
        scored = sorted(
            ((r, EMBED_WEIGHT * cosine_similarity(pe, name_embeddings[r["name_en"]])
                 + STRING_WEIGHT * _similarity(phrase, r["name_en"])) for r in catalog),
            key=lambda x: x[1], reverse=True,
        )
        top, top_score = scored[0]
        second = scored[1][1] if len(scored) > 1 else 0.0
        gap = top_score - second
        matched = top["name_en"].strip()
        answers = top_score >= MIN_CONFIDENCE

        if expected is None:
            ok = not answers
            if answers:
                false_pos.append((phrase, matched, top_score))
        else:
            ok = answers and matched.lower() == expected.lower()
            if ok:
                true_pos.append((phrase, top_score))

        verdict = "ok" if ok else "MISS"
        note = "" if expected is None else f"  (want: {expected})"
        print(f"{verdict:9} {top_score:.3f}  {gap:.3f}  {phrase[:42]:42}  "
              f"{matched[:36]}{'' if answers else '  [below threshold -> refused]'}{note}")
        for r, s in scored[1:3]:
            print(f"{'':9} {s:.3f}  {'':6}  {'':42}    runner-up: {r['name_en'].strip()[:36]}")

    print("\n" + "=" * 110)
    if false_pos:
        worst = max(s for _, _, s in false_pos)
        print(f"highest FALSE POSITIVE score: {worst:.3f}  "
              f"({[f'{p!r}->{m}' for p, m, s in false_pos if s == worst][0]})")
    else:
        print("no false positives in this set")
    if true_pos:
        lowest = min(s for _, s in true_pos)
        print(f"lowest TRUE POSITIVE score : {lowest:.3f}  "
              f"({[p for p, s in true_pos if s == lowest][0]!r})")
    else:
        print("no true positives in this set -- the threshold is refusing everything")

    if false_pos and true_pos:
        worst = max(s for _, _, s in false_pos)
        lowest = min(s for _, s in true_pos)
        if worst < lowest:
            print(f"\n=> a threshold between {worst:.3f} and {lowest:.3f} separates them cleanly. "
                  f"Suggest MIN_CONFIDENCE = {(worst + lowest) / 2:.2f}")
        else:
            print(f"\n=> NO threshold separates them: a false positive ({worst:.3f}) outscores a "
                  f"true positive ({lowest:.3f}). The scoring needs changing, not the threshold — "
                  f"try the bge-m3 query prefix, or a lower STRING_WEIGHT, since the "
                  f"solar/'Share of Qatari' collision is driven by lexical overlap.")


if __name__ == "__main__":
    main()
